/**
Test-support entry of @pace/core (`@pace/core/testing`): the artboard fixtures that the
client and the apps replay in their own tests. Never imported by production code.
*/
export {
  algebraHw6Events,
  at,
  event,
  HW_CREATED,
  HW_DUE,
  HW_ID,
  HW_PROBLEMS,
  HW_TZ,
  hwCreated,
  solved,
  stamp,
  submitted,
  subtask,
  taskFixture,
  trk231Events,
  TRK_CREATED,
  TRK_DUE,
  TRK_ID,
  TRK_NOW,
  TRK_START,
} from "./materialize/task-fixture.fake.ts";
export {
  ALGEBRA_ID,
  artboardEvents,
  artboardState,
  BOOKS_ID,
  CALC_HW5_DUE,
  CALC_HW5_ID,
  CALC_W41_ID,
  CALCULUS_ID,
  ctx,
  DEFERRED_IDS,
  DEMO_ID,
  DONE_SHEETS,
  GRADE_ID,
  HISTORY_W40_ID,
  HW_VIEW_NOW,
  INBOX_CABLE_ID,
  INBOX_GRADE_ID,
  INBOX_IDS,
  INBOX_SYNC_ID,
  INBOX_TEXTS,
  LATE_SHEETS,
  LATER_IDS,
  MOSCOW,
  NOW,
  REPLY_ID,
  RFC_ID,
  sheetId,
  WAITING_IDS,
  WORK_ID,
} from "./queries/fixture.fake.ts";
